# Generated by Django 3.2.3 on 2021-06-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Contacted', 'Contacted'), ('Packed', 'Packed'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Accepted', max_length=9),
        ),
    ]
